version: '3.8'
services:
  db:
    container_name: postgresdb
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: potter_db_api_development
    ports:
      - "5432:5432"
    restart: always

  web:
    build: .
    container_name: railsapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    command: ["sh", "-c", "rails server -b 0.0.0.0"]
